# 通过 Github actions， 在 Github 仓库的每一次 commit 后自动同步到 Gitee 上
on:
  workflow_dispatch:

name: Mirror GitHub Selected Repos to Gitee

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Mirror Github to Gitee with white list
      uses: Yikun/hub-mirror-action@master
      with:
        src: https://github.com/Squirrel223/Selfuse.git
        dst: https://github.com/Squirrel223/Selfuse.git
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.ACCESS_TOKEN }}
        force_update: true
        debug: true
